version: '3'

services:
  mongo-accounts:
    image: "mongo:latest"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod
    networks:
      - default

  accounts-frontend:
    build:
      context: "./frontend-example"
      args:
        - REACT_APP_ACCOUNT_API=http://localhost:3333
    environment:
      - NODE_ENV=production
    expose:
      - "8000"
    ports:
      - "8000:80/tcp"
    networks:
      - default

  accounts-backend:
    build: "./backend-example"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - MONGODB_HOST=mongo-accounts
      - MONGODB_DATABASE=accounts
      - FRONTEND_URL=http://localhost:8000
      - WAIT_HOSTS=mongo-accounts:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    expose:
      - "3333"
    ports:
      - "3333:3333/tcp"
    depends_on:
      - mongo-accounts
      - accounts-frontend
    command: sh -c "/wait && npm run start"
    networks:
      - default



